global:
  scrape_interval: 3s

  external_labels:
    monitor: "ecommerce-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "ecommerce"
    static_configs:
      - targets: ["api:5000"]
