"""Making tags non-unique

Revision ID: 6da3d858eb37
Revises: 4721570736b0
Create Date: 2022-05-22 10:53:50.506716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da3d858eb37'
down_revision = '4721570736b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_name_key', 'tag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tag_name_key', 'tag', ['name'])
    # ### end Alembic commands ###
